[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ato = "6Xqiy6ZcCm54aSbNd5uXrDko3tMZGf5zVhBYykzNHkJJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/scenario.ts"
